/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "ExpPol2.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

 ExpPol2::ExpPol2(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _c1,
                        RooAbsReal& _c2,
                        RooAbsReal& _beta) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   c1("c1","c1",this,_c1),
   c2("c2","c2",this,_c2),
   beta("beta","beta",this,_beta)

 {
 }


 ExpPol2::ExpPol2(const ExpPol2& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   c1("c1",this,other.c1),
   c2("c2",this,other.c2),
   beta("beta",this,other.beta)
 {
 }


 Double_t ExpPol2::evaluate() const
 {
   return ((1 + c1*x + c2*x*x)*exp(beta*x));
 }
