/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "Pol1OverPol2.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"


 Pol1OverPol2::Pol1OverPol2(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _a0,
                        RooAbsReal& _a1,
                        RooAbsReal& _b1,
                        RooAbsReal& _b2) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   a0("a0","a0",this,_a0),
   a1("a1","a1",this,_a1),
   b1("b1","b1",this,_b1),
   b2("b2","b2",this,_b2)

 {
 }


 Pol1OverPol2::Pol1OverPol2(const Pol1OverPol2& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   a0("a0",this,other.a0),
   a1("a1",this,other.a1),
   b1("b1",this,other.b1),
   b2("b2",this,other.b2)
 {
 }


 Double_t Pol1OverPol2::evaluate() const
 {
   Double_t r = (a0 + a1*x)/(1+ b1*x +b2*x*x);

   if(r>0) return r;
   else return 0;
 }
