/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "VariableWidthGaus.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"


 VariableWidthGaus::VariableWidthGaus(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _x0,
                        RooAbsReal& _alpha,
                        RooAbsReal& _beta) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   x0("x0","x0",this,_x0),
   alpha("alpha","alpha",this,_alpha),
   beta("beta","beta",this,_beta)
 {
 }


 VariableWidthGaus::VariableWidthGaus(const VariableWidthGaus& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   x0("x0",this,other.x0),
   alpha("alpha",this,other.alpha),
   beta("beta",this,other.beta)
 {
 }



 Double_t VariableWidthGaus::evaluate() const
 {
   Double_t sigma = alpha + beta*((x-x0)/x0);
   return(TMath::Exp(-0.5*TMath::Power(x-x0,2)/TMath::Power(sigma,2)));
 }
