/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "DoubleExpo.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

 DoubleExpo::DoubleExpo(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _beta1,
                        RooAbsReal& _alpha2,
                        RooAbsReal& _beta2) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   beta1("beta1","beta1",this,_beta1),
   alpha2("alpha2","alpha2",this,_alpha2),
   beta2("beta2","beta2",this,_beta2)


 {
 }


 DoubleExpo::DoubleExpo(const DoubleExpo& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   beta1("beta1",this,other.beta1),
   alpha2("alpha2",this,other.alpha2),
   beta2("beta2",this,other.beta2)
 {
 }


 Double_t DoubleExpo::evaluate() const
 {
   return (exp(beta1*x) + alpha2*exp(beta2*x));
 }
