/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef DOUBLECRYSTALBALLSHIFTED
#define DOUBLECRYSTALBALLSHIFTED

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"


class DoubleCrystalBallShifted : public RooAbsPdf {
public:
  DoubleCrystalBallShifted() {} ;
  DoubleCrystalBallShifted(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _x0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _n,
	      RooAbsReal& _alphaPrime,
	      RooAbsReal& _nPrime);
  DoubleCrystalBallShifted(const DoubleCrystalBallShifted& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new DoubleCrystalBallShifted(*this,newname); }
  inline virtual ~DoubleCrystalBallShifted() { }

protected:

  RooRealProxy x ;
  RooRealProxy x0 ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  RooRealProxy alphaPrime ;
  RooRealProxy nPrime ;
  int sign(Double_t x) const;
  Double_t evaluate() const ;

private:

  ClassDef(DoubleCrystalBallShifted,1) // Your description goes here...
};

#endif
