/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef EXPPOL2
#define EXPPOL2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class ExpPol2 : public RooAbsPdf {
public:
  ExpPol2() {} ;
  ExpPol2(const char *name, const char *title,
	      RooAbsReal& _x,
        RooAbsReal& _c1,
	      RooAbsReal& _c2,
	      RooAbsReal& _beta);
  ExpPol2(const ExpPol2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ExpPol2(*this,newname); }
  inline virtual ~ExpPol2() { }

protected:

  RooRealProxy x ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;
  RooRealProxy beta ;

  Double_t evaluate() const ;

private:

  ClassDef(ExpPol2,2) // Your description goes here...
};

#endif
