/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef NASIXTY
#define NASIXTY

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class NASixty : public RooAbsPdf {
public:
  NASixty() {} ;
  NASixty(const char *name, const char *title,
	      RooAbsReal& _x,
        Double_t _alphal,
        Double_t _pl1,
        Double_t _pl2,
        Double_t _pl3,
        Double_t _alphar,
        Double_t _pr1,
        Double_t _pr2,
        Double_t _pr3,
	      RooAbsReal& _x0,
        Double_t    _x0Shift,
	      RooAbsReal& _sigma,
        Double_t    _sigmaShift);
  NASixty(const NASixty& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new NASixty(*this,newname); }
  inline virtual ~NASixty() { }

protected:

  RooRealProxy x ;
  Double_t alphal;
  Double_t pl1;
  Double_t pl2;
  Double_t pl3;
  Double_t alphar;
  Double_t pr1;
  Double_t pr2;
  Double_t pr3;
  RooRealProxy x0 ;
  Double_t x0Shift;
  RooRealProxy sigma ;
  Double_t sigmaShift;
  Double_t evaluate() const ;

private:

  ClassDef(NASixty,2) // Your description goes here...
};

#endif
