/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef NASIXTYSHIFTED
#define NASIXTYSHIFTED

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class NASixtyShifted : public RooAbsPdf {
public:
  NASixtyShifted() {} ;
  NASixtyShifted(const char *name, const char *title,
	      RooAbsReal& _x,
        Double_t _alphal,
        Double_t _pl1,
        Double_t _pl2,
        Double_t _pl3,
        Double_t _alphar,
        Double_t _pr1,
        Double_t _pr2,
        Double_t _pr3,
	      RooAbsReal& _x0,
	      RooAbsReal& _sigma);
  NASixtyShifted(const NASixtyShifted& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new NASixtyShifted(*this,newname); }
  inline virtual ~NASixtyShifted() { }

protected:

  RooRealProxy x ;
  Double_t alphal;
  Double_t pl1;
  Double_t pl2;
  Double_t pl3;
  Double_t alphar;
  Double_t pr1;
  Double_t pr2;
  Double_t pr3;
  RooRealProxy x0 ;
  RooRealProxy sigma ;
  Double_t evaluate() const ;

private:

  ClassDef(NASixtyShifted,2) // Your description goes here...
};

#endif
