/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/
 
#ifndef POL2OVERPOL3
#define POL2OVERPOL3

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class Pol2OverPol3 : public RooAbsPdf {
public:
  Pol2OverPol3() {} ;
  Pol2OverPol3(const char *name, const char *title,
	      RooAbsReal& _x,
        RooAbsReal& _a0,
        RooAbsReal& _a1,
	      RooAbsReal& _a2,
        RooAbsReal& _b1,
        RooAbsReal& _b2,
        RooAbsReal& _b3);
  Pol2OverPol3(const Pol2OverPol3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Pol2OverPol3(*this,newname); }
  inline virtual ~Pol2OverPol3() { }

protected:

  RooRealProxy x ;
  RooRealProxy a0 ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy b1 ;
  RooRealProxy b2 ;
  RooRealProxy b3 ;

  Double_t evaluate() const ;

private:

  ClassDef(Pol2OverPol3,2) // Your description goes here...
};

#endif
