/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef VARIABLEWIDTHGAUS2
#define VARIABLEWIDTHGAUS2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class VariableWidthGaus2 : public RooAbsPdf {
public:
  //VariableWidthGaus2() {} ;
  VariableWidthGaus2(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _x0,
	      RooAbsReal& _alpha,
        RooAbsReal& _beta,
	      RooAbsReal& _gamma);
  VariableWidthGaus2(const VariableWidthGaus2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new VariableWidthGaus2(*this,newname); }

protected:

  RooRealProxy x ;
  RooRealProxy x0 ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  RooRealProxy gamma ;

  Double_t evaluate() const ;

private:

  ClassDef(VariableWidthGaus2,2) // Your description goes here...
};

#endif
